"""Create columns and Foreign Keys to 'category', 'friend', 'meal' and 'recipe' tables for 'user' table

Revision ID: 1d5ced476289
Revises: 27beffe8d1c5
Create Date: 2015-10-06 00:38:16.161660

"""

# revision identifiers, used by Alembic.
revision = '1d5ced476289'
down_revision = '27beffe8d1c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_category_user', 'category', 'user', ['user_id'], ['id'])
    op.add_column('friend', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_friend_user', 'friend', 'user', ['user_id'], ['id'])
    op.add_column('meal', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_meal_user', 'meal', 'user', ['user_id'], ['id'])
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_recipe_user', 'recipe', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recipe_user', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'user_id')
    op.drop_constraint('fk_meal_user', 'meal', type_='foreignkey')
    op.drop_column('meal', 'user_id')
    op.drop_constraint('fk_friend_user', 'friend', type_='foreignkey')
    op.drop_column('friend', 'user_id')
    op.drop_constraint('fk_category_user', 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    ### end Alembic commands ###
