"""empty message

Revision ID: 2f489a21265c
Revises: 514a5b5ac8fb
Create Date: 2015-08-22 11:25:35.808475

"""

# revision identifiers, used by Alembic.
revision = '2f489a21265c'
down_revision = '514a5b5ac8fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'meal_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cooking')
    ### end Alembic commands ###
