"""Create 'friend' table

Revision ID: 3a5de6b4bb46
Revises: 41ad1d5789df
Create Date: 2015-08-22 10:19:19.325301

"""

# revision identifiers, used by Alembic.
revision = '3a5de6b4bb46'
down_revision = '41ad1d5789df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend')
    ### end Alembic commands ###
