"""Create basic 'meal' table

Revision ID: 41ad1d5789df
Revises: None
Create Date: 2015-07-06 23:30:36.757778

"""

# revision identifiers, used by Alembic.
revision = '41ad1d5789df'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP, server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    ### end Alembic commands ###
