"""Creates 'mark' table - Adds 'description', 'reference' and 'mark_id' columns to 'recipe' table


Revision ID: 5d3b473ac52
Revises: 1d5ced476289
Create Date: 2015-10-07 22:04:33.359008

"""

# revision identifiers, used by Alembic.
revision = '5d3b473ac52'
down_revision = '1d5ced476289'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SMALLINT(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.add_column(u'recipe', sa.Column('description', sa.Text(), nullable=True))
    op.add_column(u'recipe', sa.Column('mark_id', sa.Integer(), nullable=True))
    op.add_column(u'recipe', sa.Column('reference', sa.String(length=255), nullable=True))
    op.create_foreign_key('fk_recipe_mark', 'recipe', 'mark', ['mark_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recipe_mark', 'recipe', type_='foreignkey')
    op.drop_column(u'recipe', 'reference')
    op.drop_column(u'recipe', 'mark_id')
    op.drop_column(u'recipe', 'description')
    op.drop_table('mark')
    ### end Alembic commands ###
